### ISSUE TITLE
Suggestion - zero map on search postcode

### ISSUE THREAD

**Issue by robmarkcole** [dsharpc/StreamlitCrime#1]
As title

**Comment by dsharpc** [comment]
Hi Robin,

Thanks for this. That would definitely be the best user experience, however, as far as I'm aware it is not yet possible. Streamlit developers are aware though: https://github.com/streamlit/streamlit/issues/475

I'll definitely update as soon as this becomes available.

**Comment by dsharpc** [comment]
Hi Rob, 

Thanks again for your comment. It's been a long time, but I've now fixed the map to automatically focus on search postcode.

Thanks for your feedback!
